#!/usr/bin/env bash
# copies file over scp
if [[ $# == 4 ]]; then
    scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:/home/$3
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
