#!/usr/bin/env bash
# configures nginx
apt-get update -y
apt-get install nginx -y
touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
redir="server_name peytonsmith.tech;\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}"
sed -i "s/server_name _;/$redir/" /etc/nginx/sites-available/default
service nginx restart
