#!/usr/bin/env bash
# configures nginx
apt-get install nginx -y
touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
touch /var/www/html/error.html
echo "Ceci n'est pas une page" > /var/www/html/error.html
redir="\tlocation /redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\n\t}"
error="\n\terror_page 404 \/error.html;\n"
sed -r -i "/^\s+server_name _;/a\ $redir$error" /etc/nginx/sites-available/default
sed -r -i "/^\s+server_name _;/a\ $redir$error" /etc/nginx/sites-enabled/default
service nginx restart
