#!/usr/bin/env bash
# configures nginx with hostname http header
string="\tadd_header X-Served-By \$hostname;"
sed -r -i "/^\s+server_name _;/a\ $string" /etc/nginx/sites-available/default
sed -r -i "/^\s+server_name _;/a\ $string" /etc/nginx/sites-enabled/default
service nginx restart
