#!/usr/bin/env bash
# installs/configures haproxy
apt-get update
apt-get install -y haproxy=1.6.\*

init="ENABLED=1"

echo -e "\n$init" >> /etc/default/haproxy

proxy="frontend http
        bind *:80
        mode http

        default_backend web-backend

backend web-backend
        balance roundrobin
        mode http
        server web-01 34.74.188.209:80
        server web-02 54.226.48.62:80"

echo -e "$proxy" >> /etc/haproxy/haproxy.cfg

service haproxy restart
